Fix toolchain auto installation through rustup-toolchain-install-master
rustup no longer uses 101 exit code when it fails to locate the toolchain:

```console
$ rustup which rustc --toolchain f426146460c5446bb41ac0b677bbfe5b6ff502ba
error: toolchain 'f426146460c5446bb41ac0b677bbfe5b6ff502ba' is not installed
$ echo $?
1
```