feat: support `@argfile` for rustc-fake
This PR includes

* A verbatim copy of `arg_file_command.rs` from rust-lang/rust
* adapted copies of some other helpers from bootstrap.

This found because we tried to enable new build-dir layout for nightly
in Cargo, but failed with

```
error: Unrecognized option: 'skip-this-rustc'
```

I _guess_ this was the root cause.

See

* https://triage.rust-lang.org/gha-logs/rust-lang/rust/89681531404
* https://github.com/rust-lang/rust/pull/159857#issuecomment-5078882351